"""create auto table

Revision ID: ef94c89f4b97
Revises: 9041334a30bd
Create Date: 2023-09-30 11:29:03.875698

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef94c89f4b97"
down_revision: Union[str, None] = "9041334a30bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto",
        sa.Column("brand", sa.String(length=50), nullable=False),
        sa.Column("park_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["park_id"],
            ["park.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auto")
    # ### end Alembic commands ###
