"""create TrafficUnit table

Revision ID: 46f60acc344b
Revises: 95992f467180
Create Date: 2023-09-30 21:44:52.366390

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46f60acc344b"
down_revision: Union[str, None] = "95992f467180"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "route",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_point", sa.String(length=50), nullable=False),
        sa.Column("end_point", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trafficunit",
        sa.Column("transport_unit_id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transport_unit_id"],
            ["transportunit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transport_unit_id", "route_id", name="unique_traffic_unit"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trafficunit")
    op.drop_table("route")
    # ### end Alembic commands ###
