"""create park table

Revision ID: 9041334a30bd
Revises: 3e22a652ed8a
Create Date: 2023-09-29 11:21:35.350335

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9041334a30bd"
down_revision: Union[str, None] = "3e22a652ed8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "park",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parkowner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parkowner_id"],
            ["parkowner.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("park")
    # ### end Alembic commands ###
